### ISSUE TITLE
BarrierUnknownFailed. nni pod remains permanently in Init state

### ISSUE THREAD

**Issue by mf-giwoong-lee** [microsoft/frameworkcontroller#64]
[https://nni.readthedocs.io/en/stable/TrainingService/FrameworkControllerMode.html](url)
I follow this istruction to train my model with nni + kubernetes.

nniexp pod remains in Init state. It didn't start the experiment.

kubectl describe pod nniexp returns these messages.

```
Controlled By:  ConfigMap/nniexpshhbauzetrialhm50l-attempt
Init Containers:
  frameworkbarrier:
    Container ID:  docker://e4cc0c27a6ca206698dbcee976010a4b039f7d0e0aed8e3eaf1ebe32a186caca
    Image:         frameworkcontroller/frameworkbarrier
    Image ID:      docker-pullable://frameworkcontroller/frameworkbarrier@sha256:4f56b0f70d060ab610bc72d994311432565143cd4bb2613916425f8f3e80c69f
    Port:          <none>
    Host Port:     <none>
    State:         Running
      Started:     Fri, 03 Sep 2021 13:43:04 +0900
    Last State:    Terminated
      Reason:      Error
      Message:     Framework object from ApiServer: frameworks.frameworkcontroller.microsoft.com "nniexpshhbauzetrialhm50l" is forbidden: User "system:serviceaccount:default:default" cannot get resource "frameworks" in API group "frameworkcontroller.microsoft.com" in the namespace "default"
W0903 04:42:40.232306       9 barrier.go:253] Failed to get Framework object from ApiServer: frameworks.frameworkcontroller.microsoft.com "nniexpshhbauzetrialhm50l" is forbidden: User "system:serviceaccount:default:default" cannot get resource "frameworks" in API group "frameworkcontroller.microsoft.com" in the namespace "default"
W0903 04:42:50.259713       9 barrier.go:253] Failed to get Framework object from ApiServer: frameworks.frameworkcontroller.microsoft.com "nniexpshhbauzetrialhm50l" is forbidden: User "system:serviceaccount:default:default" cannot get resource "frameworks" in API group "frameworkcontroller.microsoft.com" in the namespace "default"
W0903 04:43:00.259436       9 barrier.go:253] Failed to get Framework object from ApiServer: frameworks.frameworkcontroller.microsoft.com "nniexpshhbauzetrialhm50l" is forbidden: User "system:serviceaccount:default:default" cannot get resource "frameworks" in API group "frameworkcontroller.microsoft.com" in the namespace "default"
W0903 04:43:00.260439       9 barrier.go:253] Failed to get Framework object from ApiServer: frameworks.frameworkcontroller.microsoft.com "nniexpshhbauzetrialhm50l" is forbidden: User "system:serviceaccount:default:default" cannot get resource "frameworks" in API group "frameworkcontroller.microsoft.com" in the namespace "default"
E0903 04:43:00.260455       9 barrier.go:283] BarrierUnknownFailed: frameworks.frameworkcontroller.microsoft.com "nniexpshhbauzetrialhm50l" is forbidden: User "system:serviceaccount:default:default" cannot get resource "frameworks" in API group "frameworkcontroller.microsoft.com" in the namespace "default"
E0903 04:43:00.260466       9 barrier.go:470] ExitCode: 1: Exit with unknown failure to tell controller to retry within maxRetryCount.

      Exit Code:    1
      Started:      Fri, 03 Sep 2021 13:33:00 +0900
      Finished:     Fri, 03 Sep 2021 13:43:00 +0900
    Ready:          False
    Restart Count:  4
    Environment:
      FC_FRAMEWORK_NAMESPACE:             default
      FC_FRAMEWORK_NAME:                  nniexpshhbauzetrialhm50l
      FC_TASKROLE_NAME:                   worker
      FC_TASK_INDEX:                      0
      FC_CONFIGMAP_NAME:                  nniexpshhbauzetrialhm50l-attempt
      FC_POD_NAME:                        nniexpshhbauzetrialhm50l-worker-0
      FC_FRAMEWORK_UID:                   68bb7a39-2209-407c-9c37-5e4e449a9afb
      FC_FRAMEWORK_ATTEMPT_ID:            0
      FC_FRAMEWORK_ATTEMPT_INSTANCE_UID:  0_acfe3e48-99ad-44fb-88bc-9024c99b01c3
      FC_CONFIGMAP_UID:                   acfe3e48-99ad-44fb-88bc-9024c99b01c3
      FC_TASKROLE_UID:                    c57048a6-0c6b-11ec-b7f1-0242ac110006
      FC_TASK_UID:                        c5704927-0c6b-11ec-b7f1-0242ac110006
      FC_TASK_ATTEMPT_ID:                 0
      FC_POD_UID:                          (v1:metadata.uid)
      FC_TASK_ATTEMPT_INSTANCE_UID:       0_$(FC_POD_UID)
    Mounts:
      /mnt/frameworkbarrier from frameworkbarrier-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wthsw (ro)
Containers:
  framework:
    Container ID:
    Image:         msranni/nni:latest
    Image ID:
    Port:          4000/TCP
    Host Port:     0/TCP
    Command:
      sh
      /tmp/mount/nni/SHhbAuZE/hm50L/run_worker.sh
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:             1
      memory:          8Gi
      nvidia.com/gpu:  1
    Requests:
      cpu:             1
      memory:          8Gi
      nvidia.com/gpu:  1
    Environment:
      FC_FRAMEWORK_NAMESPACE:             default
      FC_FRAMEWORK_NAME:                  nniexpshhbauzetrialhm50l
      FC_TASKROLE_NAME:                   worker
      FC_TASK_INDEX:                      0
      FC_CONFIGMAP_NAME:                  nniexpshhbauzetrialhm50l-attempt
      FC_POD_NAME:                        nniexpshhbauzetrialhm50l-worker-0
      FC_FRAMEWORK_UID:                   68bb7a39-2209-407c-9c37-5e4e449a9afb
      FC_FRAMEWORK_ATTEMPT_ID:            0
      FC_FRAMEWORK_ATTEMPT_INSTANCE_UID:  0_acfe3e48-99ad-44fb-88bc-9024c99b01c3
      FC_CONFIGMAP_UID:                   acfe3e48-99ad-44fb-88bc-9024c99b01c3
      FC_TASKROLE_UID:                    c57048a6-0c6b-11ec-b7f1-0242ac110006
      FC_TASK_UID:                        c5704927-0c6b-11ec-b7f1-0242ac110006
      FC_TASK_ATTEMPT_ID:                 0
      FC_POD_UID:                          (v1:metadata.uid)
      FC_TASK_ATTEMPT_INSTANCE_UID:       0_$(FC_POD_UID)
    Mounts:
      /mnt/frameworkbarrier from frameworkbarrier-volume (rw)
      /tmp/mount from nni-vol (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wthsw (ro)
Conditions:
  Type              Status
  Initialized       False
  Ready             False
  ContainersReady   False
  PodScheduled      True
```

I paste the part of messages. If you need full log messages, then I upload it later.

I executed the programs in this order:
1. launch minikube with --driver=none, api-server=127.0.0.1
2. launch k8s-nvidia-daemonset
3. launch framework controller
4. launch nnictl

My minikube config is here:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/gwlee/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Fri, 03 Sep 2021 09:23:56 KST
        provider: minikube.sigs.k8s.io
        version: v1.22.0
      name: cluster_info
    server: https://localhost:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Fri, 03 Sep 2021 09:23:56 KST
        provider: minikube.sigs.k8s.io
        version: v1.22.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/gwlee/.minikube/profiles/minikube/client.crt
    client-key: /home/gwlee/.minikube/profiles/minikube/client.key
```
