### ISSUE TITLE
[Question] How to raise the size of shared memory when running NNI frameworkcontroller?

### ISSUE THREAD

**Issue by mf-giwoong-lee** [microsoft/frameworkcontroller#67]
I used the frameworkcontroller as NNI training platform. So this question is not proper in here. Sorry for about it but I really want to find the answer...

Just you know, pytorch dataloader uses shared memory and k8s assigns 64MB as size of shared memory.

But it is not sufficient in real scenario, so I want to increase the size of shared memory.

But NNI has no options for this and I was trying to edit `frameworkcontroller.yaml` like below YAML but it was not working.

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: frameworkcontroller-shm
  namespace: default
spec:
  serviceName: frameworkcontroller-shm
  selector:
    matchLabels:
      app: frameworkcontroller-shm
  replicas: 1
  template:
    metadata:
      labels:
        app: frameworkcontroller-shm
    spec:
      # Using the ServiceAccount with granted permission
      # if the k8s cluster enforces authorization.
      serviceAccountName: frameworkcontroller-shm
      containers:
      - name: frameworkcontroller-shm
        image: frameworkcontroller/frameworkcontroller
        volumeMounts:
        - name: shm-volume
          mountPath: /dev/shm
      volumes:
        - name: shm-volume
          emptyDir:
            medium: Memory
```

Is there any solution or idea to solve this problem?
