### ISSUE TITLE
Having trouble when tried NNI with FrameworkController on-premise k8s

### ISSUE THREAD

**Issue by juniroc** [microsoft/frameworkcontroller#73]
### when i tried nni with FrameworkController on on-premise k8s

I followed this document 
https://nni.readthedocs.io/en/stable/TrainingService/FrameworkControllerMode.html

- create Serviceaccount and clusterrolebinding
```
kubectl create serviceaccount frameworkcontroller --namespace default
kubectl create clusterrolebinding frameworkcontroller \
  --clusterrole=cluster-admin \
  --user=system:serviceaccount:default:frameworkcontroller
```

- and set StatefulSet
`framework-config.yml`
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: frameworkcontroller
  namespace: default
spec:
  serviceName: frameworkcontroller
  selector:
    matchLabels:
      app: frameworkcontroller
  replicas: 1
  template:
    metadata:
      labels:
        app: frameworkcontroller
    spec:
      # Using the ServiceAccount with granted permission
      # if the k8s cluster enforces authorization.
      serviceAccountName: frameworkcontroller
      containers:
      - name: frameworkcontroller
        image: frameworkcontroller/frameworkcontroller
        # Using k8s inClusterConfig, so usually, no need to specify
        # KUBE_APISERVER_ADDRESS or KUBECONFIG
#        env:
        #- name: KUBE_APISERVER_ADDRESS
        #  value: {http[s]://host:port}
#          - name: KUBECONFIG
#            value: ~/.kube/config
```

```
kubectl apply -f framework-config.yml
```

and when I tried `kubectl get po`
<img width="436" alt="image" src="https://user-images.githubusercontent.com/58424182/155088623-b3b3180f-1986-4cd7-b69e-b78f76e9110a.png">

and tried `kubectl logs frameworkcontroller-0`

![image](https://user-images.githubusercontent.com/58424182/155088567-d78af913-7ed4-451c-981a-4d527b5f49a1.png)

It said
```
updateRemoteFrameworkStatus: 
Failed: Framework.frameworkcontroller.microsoft.com "nniexpqfwzydmkenvfpwjw" is invalid:
spec.taskRoles.task.podGracefulDeletionTimeoutSec: Invalid value: "null":
spec.taskRoles.task.podGracefulDeletionTimeoutSec in body must be of type integer: "null"
```

what should I do to solve this problem?
