### ISSUE TITLE
[Question] Node selector for framework

### ISSUE THREAD

**Issue by mf-giwoong-lee** [microsoft/frameworkcontroller#76]
I am working with NNI on k8s.

Thanks to frameworkcontroller, I has worked with NNI more easily.

Recently, I am digging hardly to construct k8s training system and I have a question about frameworkcontroller.

Frameworkcontroller consumes frameworks to create pods for NNI. So I edited framework format in NNI codes to allocate pods to desired nodes.

To do this, I added a node selector to framework format in NNI codes but it was not working.

Is there any guides or ways to allocates pods from frameworks to desired nodes like node selector?

**Comment by yqwang-ms** [comment]
The k8s [NodeSelector](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/) should work with Frameworkcontroller, see one example below:
```yaml

# For the full spec setting and usage, see ./pkg/apis/frameworkcontroller/v1/types.go
apiVersion: frameworkcontroller.microsoft.com/v1
kind: Framework
metadata:
  name: batchsucceeded
spec:
  executionType: Start
  retryPolicy:
    fancyRetryPolicy: true
    maxRetryCount: 1
  taskRoles:
  - name: worker
    taskNumber: 1
    frameworkAttemptCompletionPolicy:
      minFailedTaskCount: 1
      minSucceededTaskCount: -1
    task:
      retryPolicy:
        fancyRetryPolicy: true
        maxRetryCount: 1
      podGracefulDeletionTimeoutSec: 600
      pod:
        spec:
          restartPolicy: Never
          containers:
          - name: ubuntu
            image: ubuntu:trusty
            command: ["sh", "-c", "printenv && sleep 10"]
          nodeSelector:
            disktype: ssd
```

> I added a node selector to framework format in NNI codes
How did you add this?
Can you give us the framework object after NNI submit your new framework format? (And you can check if that still contains nodeSelector)
